name: fitness-bot

on:
  workflow_dispatch:   # 🟢 手动触发（必须有）
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 4 * * *"
    - cron: "0 8 * * *"
    - cron: "0 12 * * *"
    - cron: "0 18 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install requests

      - run: python main.py
